/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ETHStakeBridge } from "./ETHStakeBridge";
export * as factories from "./factories";
export { ETHStakeBridge__factory } from "./factories/ETHStakeBridge__factory";
